name: SSH Remote Commands
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Execute SSH commmands on remote server
      uses: JimCronqvist/action-ssh@master
      env:
       NAME: "Root"
      with:
       hosts: 'user@domain.com user@domain2.com:2222'
       privateKey: ${{ secrets.PRIVATE_KEY }}
       debug: false
       command: |
        ls -lah
        echo "I am $NAME"
