name: SSH Remote Commands
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Execute SSH commmands on remote server
      uses: JimCronqvist/action-ssh@master
      with:
        hosts: '15.206.207.59'
        privateKey: ${{ secrets.PRIVATE_KEY }}
        command: ls -lah
