name: git shell commands

on: [push]

jobs:
  to-run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "hello"
      - name: multiline command
        run: |
          npm -v
          node -v
  to-run-windows-commands:
    runs-on: windows-latest
    steps:
      - name: directory windows
        run: Get-location
      - name: directory bash
        run: pwd
        shell: bash  


