name: git shell commands

on: [push]

jobs:
  to-run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "hello"
      - name: multiline command
        run: |
          npm -v
          node -v

    


